# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IRF_genmap <- function(bam_file, output_path) {
    .Call(`_rIRFinder_IRF_genmap`, bam_file, output_path)
}

IRF_main <- function(bam_file, reference_path, output_path) {
    .Call(`_rIRFinder_IRF_main`, bam_file, reference_path, output_path)
}

rcpparma_hello_world <- function() {
    .Call(`_rIRFinder_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_rIRFinder_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_rIRFinder_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_rIRFinder_rcpparma_bothproducts`, x)
}

